run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  revive:
    rules:
      - name: exported
        disabled: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - makezero
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - tparallel
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-use-default: false
  exclude: []
  max-issues-per-linter: 0
  max-same-issues: 0
